### PR TITLE
🐞 fix: prevent failure & add error messages on failed refresh attempts

### PR DESCRIPTION
**Pull request by m1212e**
Describe your PR <3

### CODE REVIEW

**Comment by m1212e** [comment]
@TadeSF In the current implementation, when a token set is found but the access token is expired, the app will try to refresh it. If that failed too, the request will be rejected with a forbidden status, just as if you were not logged in properly. A page reload will then trigger a new login flow. I did not include an automatic redirect to the / path since this might lead to loss of data in e.g. forms which might not be saved/submitted yet. We could discuss a custom error message which suggests reloading the page to get a fresh login flow & a corresponding session. Whats your take on this?

**Comment by TadeSF** [comment]
@m1212e thanks! Sounds good. A popup modal that suggests updating the data seems like the best solution to me as well. But the initial flow remains untouchted on actual sign up, do I understand that correctly?

**Comment by m1212e** [comment]
Yes the flow stays the same for the user.

**Comment by m1212e** [comment]
Basically now they just get a proper error toast which asks them to reload the page which will trigger a fresh login flow instead of doing nothing and having the api respond with some error code

**Review by TadeSF — APPROVED** [review]
Thanks!

**Pull request merged**
