### PR TITLE
📚 Language improvements for the chatbot

### PR DESCRIPTION
**Pull request by Amselfass**
Updated language for the chatbot according to the principles laid out in #68.

I changed the .svelte files so that the button texts in the chatbot are now (hopefully) set by localization instead of being hard-coded. Afaik, I have no way of testing if this actually works, so please have a quick look whether I goofed it up. :-)

### CODE REVIEW

**Comment by Amselfass** [comment]
Sorry guys, this apparently fails the build, so definitely don't merge this as is. Who could have predicted that editing code files without any knowledge about the syntax would cause this? :D

It's probably pretty clear what I wanted to do – if it is a very quick fix, you can edit the PR, but otherwise, I'll make a new version without the build-breaking changes to spare you the work.

**Comment by TadeSF** [comment]
Thanks @Amselfass!! Its almost perfect, just a small syntactical thing: you don't need the `{}` within the `<script>` `</script>` tags. Those are only for svelte in the normal html sections important, to actually be able to call the functions instead of just printing what is written.

Within the script tags, the language is plain typescript and therefore there is no need to escape anything to call a language function ;)

**Review by TadeSF — APPROVED** [review]
Looks good! Thanks for your help!

**Comment by Amselfass** [comment]
Thanks for the help. :-)

**Pull request merged**
